### ISSUE TITLE
FirebaseListAdapter crashes when $priority is updated

### ISSUE THREAD

**Issue by mattblang** [firebase/AndroidChat#20]
Whenever I update `$priority` from my web app, the [FirebaseListAdapter.java](https://github.com/firebase/AndroidChat/blob/master/app/src/main/java/com/firebase/androidchat/FirebaseListAdapter.java) that I am using in my Android app causes a crash.  [Here is a gist](https://gist.github.com/mattblang/19be72c27a4da050c847) of the stacktrace.

**Comment by puf** [comment]
Let me know if the problem remains. Open a new issue if my changes introduce new problems.

**Comment by mattblang** [comment]
@puf Works great!  Thank you so much.
