### ISSUE TITLE
3 or more continuous messages sent doesn't get displayed.

### ISSUE THREAD

**Issue by vipulasri** [firebase/AndroidChat#28]
3 or more continuous messages sent doesn't get displayed, unless a new message from different user receives but still those messages are lost.

**Comment by puf** [comment]
This sounds like a network connectivity issue. To help you troubleshoot, you may want to [enable debug logging](https://www.firebase.com/docs/android/api/#config_setLogLevel) and see what's going on.

**Comment by abehaskins** [comment]
No response in 3+ months, closing.
