### ISSUE TITLE
Opened project and Run it. But Directly disconnected is written on toast!

### ISSUE THREAD

**Issue by emreer93** [firebase/AndroidChat#30]
I am new developer on android. I downloaded project and tried to have an account on Firebase. I tried to find url. I found a URL which is correct or not to connect my firebase!?. Then I run app but toast is written disconnected from firebase. I couldnt understand to use firebase and your app to be connected. Could you help me to run this app please?

**Comment by abehaskins** [comment]
This is a legacy sample which uses the old SDK version.

I'd recommend checking out the [Getting Started guide](https://firebase.google.com/docs/android/setup) for the newer SDK since it'll walk you through how to configure a project with your Firebase info.

All the best,
abe
