### ISSUE TITLE
I have created an app in firebase Unable to find YOUR FIREBASE APP

### ISSUE THREAD

**Issue by ansarisufiyan777** [firebase/AndroidChat#32]
Firebase myFirebaseRef = new Firebase("https://<YOUR-FIREBASE-APP>.firebaseio.com/");
How do i find this
I am gettig this error
 09-13 16:28:02.933 15585-15585/com.firebase.androidchat E/FirebaseListAdapter: Listen was cancelled, no more updates will occur

**Comment by abehaskins** [comment]
Hi!

This is a legacy sample which uses the old SDK version.

I'd recommend checking out the [Getting Started guide](https://firebase.google.com/docs/android/setup) for the newer SDK since it'll walk you through where to get the `<YOUR-FIREBASE-APP>` and such.

all the best,
abe
