### ISSUE TITLE
FirebaseListAdapter, onChildMoved bug

### ISSUE THREAD

**Issue by AlesKracik** [firebase/AndroidChat#6]
Hey,

I've used your implementation as basic for new RecyclerView. And noticed, that your method onChildMoved updates mModels with new object, but does not update mModelKeys. So if the same item is later being used, mModelKeys and mModel are not object consistent.

**Comment by sirvon** [comment]
any resolution in this issue?

**Comment by mimming** [comment]
Not yet. This isn't a terribly popular sample, so revisiting it was further down my to do list. But since you poked it, I'll give it some attention later today.

**Comment by sivaramsi** [comment]
I tried to implement the recent chats like whatsapp by setpriority with  respect to inverse of time ,
but when the child is moved then it throws arrayoutofbound exception

**Comment by achuinard** [comment]
I found that the modelKeys map does not get updated and that the models list now has a different version of the object. Since onChildChanged is called directly after onChildMoved, and it uses a Java indexOf to find the model, getting the oldModel from modelKeys doesn't work.

**Comment by achuinard** [comment]
I believe it's just a one-line fix, and I've created a pull request - 

https://github.com/firebase/AndroidChat/pull/15

**Comment by puf** [comment]
Hey @achuinard, sorry for missing your PR. I just committed a fix (https://github.com/firebase/AndroidChat/commit/daeb2232dc58156197680a552c7198a62ba1301e) for another issue, which probably also fixes this one. Feel free to reopen if this problem persists.
